name: Create Docker Container

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./week_ecr
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Print AWS CLI and Docker versions
        run: |
          aws --version
          docker --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 185183796631.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t mlops-1 .

      - name: Tag Docker image
        run: docker tag mlops-1:latest 185183796631.dkr.ecr.us-east-1.amazonaws.com/mlops-1:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 185183796631.dkr.ecr.us-east-1.amazonaws.com/mlops-1:latest
